### ISSUE TITLE
U.Z.1 As a user I want to see a nice UI, in order to understand what I need to do

### ISSUE THREAD

**Issue by Mariinja** [sopra-fs22-group-11/SoPra22-group11-TheGame-Client#58]
## Acceptance Criteria

- [x] UI of the Game looks nice and all important information are displayed intuitive
- [x] Homepage looks fancy 
- [x] Way of getting to the Game is intuitve
- [x] We have a consitent look and feel
## Task List
- [x] #59
- [x] #60
- [x] #61
- [x] #62
- [x] #63
- [x] #64
- [x] #65
- [x] #66
- [x] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #71

**Comment by Mariinja** [comment]
8becb82c121c2c06ba16830c1eebab4cb7682b9d[](url)
