### ISSUE TITLE
UB.3.1  Audio communication during Game: As a player I want to join a voice call to hear the other players, to make communication even easier.

### ISSUE THREAD

**Issue by Mariinja** [sopra-fs22-group-11/SoPra22-group11-TheGame-Client#74]
## Acceptance Criteria
- [ ] A player should hear the other players that have agreed to share their audio.
- [x] A user should be able to share their own audio with players after they agreed to share

## Task List
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#71
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#72
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Client#25
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Client#57
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Client#56
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#141
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#147
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#148

**Comment by Mariinja** [comment]
@Desteb code and close

**Comment by Desteb** [comment]
2b5f2331152bc3f399d0eca7c61a4d004e6aba52
