### ISSUE TITLE
UB.3.2  Mute voice during Game: As a player I want to be able to mute myself, which would allow users to play in more crowded areas without bothering the other players.

### ISSUE THREAD

**Issue by Desteb** [sopra-fs22-group-11/SoPra22-group11-TheGame-Client#75]
## Acceptance Criteria
- [x] A user should be able to mute their microphone.
- [x] A user should be able to unmute their microphone.
- [x] Other users should see my status (muted/unmuted)

## Task List
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#68
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Client#26

**Comment by Mariinja** [comment]
close again, with right milestone included
