### ISSUE TITLE
UA.3.2 Start Game: As a player waiting in the waiting room, I want to be able to start the game in order to begin playing.

### ISSUE THREAD

**Issue by Mariinja** [sopra-fs22-group-11/SoPra22-group11-TheGame-Client#76]
## Accpetance Criteria
- [x] Users in the waiting room are able to start the game.

## Task List
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#47
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#48
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#49
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#51
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Client#40
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Server#134
- [x] sopra-fs22-group-11/SoPra22-group11-TheGame-Client#54

**Comment by tikost** [comment]
191eb8f1aba6e9284d53bac651ab817e1cbd3cf1
